app = "bb-metabase"
primary_region = "sjc"

kill_signal = "SIGTERM"
kill_timeout = 5

[build]
image = "metabase/metabase:latest"

[env]
MB_DB_TYPE = "h2"
MB_DB_FILE = "/data/metabase.db"

[http_service]
internal_port = 3000
force_https = true

[http_service.concurrency]
type = "requests"
hard_limit = 150
soft_limit = 100

[[http_service.checks]]
grace_period = "120s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/api/health"

[mounts]
source = "bb_metabase_data"
destination = "/data"
