# fly.toml app configuration file generated for builderbot on 2023-05-27T14:49:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "builderbot"
primary_region = "dfw"

[env]

[vm]
  count = 1
  memory = "512"
